#!/usr/bin/env python
"""
Write the q / separation / σ / mean-q comparison figures vs SPISEA v2.5.

This is a thin runner. Each PNG is generated by its matching script:

    docs/figures/plot_q_offner_vs_spisea2.5.py
    docs/figures/plot_sep_offner_vs_spisea2.5.py
    docs/figures/plot_sig_loga_offner_vs_spisea2.5.py
    docs/figures/plot_meanq_offner_vs_spisea2.5.py

Run from the repository root::

    python docs/figures/plot_q_sep_offner_vs_spisea2.5.py
"""
import os
import runpy


_SCRIPTS = (
    'plot_q_offner_vs_spisea2.5.py',
    'plot_sep_offner_vs_spisea2.5.py',
    'plot_sig_loga_offner_vs_spisea2.5.py',
    'plot_meanq_offner_vs_spisea2.5.py',
)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    for name in _SCRIPTS:
        runpy.run_path(os.path.join(here, name), run_name='__main__')


if __name__ == '__main__':
    main()
